[project]
name = "comfyui-serverless"
handler = "runpod_handler.py"
runtime = "python:3.10"

[deployment]
endpoint_type = "serverless"
docker_image = "runpod/pytorch:2.2.0-py3.10-cuda12.1.1-devel-ubuntu22.04"
min_workers = 0
max_workers = 3
idle_timeout = 60
max_concurrency = 10

[environment]
PYTHONPATH = "/workspace/src"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"

[resources]
gpu_type = "NVIDIA GeForce RTX 3090"
gpu_count = 1
cpu_count = 4
ram_gb = 24

[build]
requirements_file = "src/requirements.txt"
setup_commands = [
    "apt-get update && apt-get install -y libpq-dev redis-server",
    "pip install --upgrade pip",
    "pip install runpod",
    "mkdir -p logs temp outputs models"
]