apiVersion: v1
kind: ConfigMap
metadata:
  name: comfyui-config
  namespace: comfyui-serverless
data:
  API_TITLE: "ComfyUI Serverless API"
  API_VERSION: "1.0.0"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8000"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  
  # Database settings
  DATABASE_POOL_SIZE: "10"
  DATABASE_MAX_OVERFLOW: "20"
  
  # Redis settings
  REDIS_QUEUE_DB: "1"
  REDIS_CACHE_DB: "2"
  
  # ComfyUI settings
  COMFYUI_PATH: "/opt/ComfyUI"
  COMFYUI_MODELS_PATH: "/opt/ComfyUI/models"
  COMFYUI_OUTPUT_PATH: "/opt/ComfyUI/output"
  COMFYUI_TEMP_PATH: "/opt/ComfyUI/temp"
  COMFYUI_API_URL: "http://localhost:8188"
  
  # GPU settings
  GPU_MEMORY_FRACTION: "0.8"
  MAX_GPU_MEMORY_GB: "24"
  ENABLE_MODEL_OFFLOAD: "true"
  MODEL_CACHE_SIZE_GB: "10"
  
  # Rate limiting
  RATE_LIMIT_PER_MINUTE: "60"
  RATE_LIMIT_PER_HOUR: "1000"
  RATE_LIMIT_PER_DAY: "10000"
  
  # Workflow execution
  MAX_EXECUTION_TIME_MINUTES: "30"
  MAX_QUEUE_SIZE: "100"
  WORKER_CONCURRENCY: "2"
  
  # File management
  MAX_FILE_SIZE: "104857600"  # 100MB
  STORAGE_TYPE: "s3"
  
  # Cleanup settings
  CLEANUP_INTERVAL_HOURS: "1"
  TEMP_FILE_RETENTION_HOURS: "24"
  RESULT_RETENTION_DAYS: "7"
  
  # Webhook settings
  WEBHOOK_TIMEOUT_SECONDS: "30"
  WEBHOOK_RETRY_ATTEMPTS: "3"
  WEBHOOK_RETRY_DELAY_SECONDS: "5"
  
  # Health checks
  HEALTH_CHECK_INTERVAL_SECONDS: "30"
  HEALTH_CHECK_TIMEOUT_SECONDS: "10"
  
  # Metrics
  ENABLE_METRICS: "true"
  METRICS_PORT: "9090"